### ISSUE TITLE
Create a procedure to manage the dead-letter messages

### ISSUE THREAD

**Issue by gtrias** [switchboardoperator/switchboard-operator#16]

**Comment by elboletaire** [comment]
Not sure we really want this... Unless you have something specific in mind @gtrias, I'll remove this issue.

Because I think dead-letters should be manually processed for each specific case, although, as said, if you have something specific in mind, I can consider it.

**Comment by gtrias** [comment]
This can be done from RabbitMQ manager with the plugin shovel, But it could be convenient to move again the dead messages to its source queue after fixing the root problem which made them fail. 
As you will see the rabbit shovel plugin is very manual stop so having this with SBO would be great.

**Comment by elboletaire** [comment]
Ok I see what you mean, but I don't really get how could we automatize this from the SBO side :thinking: 

I think that most cases will require a manual intervention at the end.

**Comment by elboletaire** [comment]
For example, I was thinking about being able to add operators specifically for dead-letters. For that I'll need first to finish standardizing the queue names (right now dead-letters are shared between operators) but, also, I think we should add a flag in operators to not create dead letters.

This way we'll avoid creating dead-letters for dead-letters, and users will be able to create operators that act on dead-letters, thus, allowing them to clean-up a dead-letter.
